---
abstract: 'Plack::Builder extension'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Builder-Conditionals
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::MoreUtils: 0
  Net::CIDR::Lite: 0
  Plack: 0.9941
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Plack-Builder-Conditionals.git
version: 0.02
